// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"vFVNb+M4DP0rBneP3thpe/ItwG6LLnYXxc4UcyhyUG3aYceSXIkKmgn83weUnQ9Pk+l8AHOjZPKJ5Huk",
	"t1Ba3VmDhj0UW3DoO2s8xsN/lq9tMJXYpTWMhsVUXddSqZisyZ68NXLnyxVqJdbvDmso4LfsAJwNX332",
	"l3PWQd/3KVToS0edgEAB/6O3wZWYGMtJHd/sU7g3KvDKOvqEvyCHf8l7Mk1iXUJmrVqqErYf0YC4jtEC",
	"PgAUW+ic7dAxDc3S6L1qUEzedAgFeHZkmhju8DmQkyoe9o7LdOdoH5+w5FixxxPQpUPFWC1i5bV1WjEU",
	"UCnGP5g0QvrliymgVtRO3IebE65UTfxCoOqUm1H6G4qLsbunYkh6lP7rkqW1WAZHvHknLR4KfkTl0C0C",
	"rw6n612Cf394DyMhgjR8PWS8Yu4GesnUVuKnNC8ST7prMQkeXaKVUQ1qNJws7m4FhbgVGGFivFqj80Ps",
	"fJbPcmmG7dCojqCAy1k+u4QUOsWrmHsmuNFqMBImTEah3lZQwD/k+T56SIxTGjm6P2yB5InngG6z610B",
	"LWniXblqqKZWoWUoLvIUtHohHTQU8zzfd4AMY4Oi8fQ0qK1rj2dQT8Es0+leuMjz7xrHqZqJUU+Nr41r",
	"nIh+n5RyTm3i2bJqj/R4VPREkINfOj52QoCv9sCdasiIYJOWPCe2TgZG+xSu8vm5fPcNyiZbKwo8aK3c",
	"ZiQ/UW07IqbAqhHuYTgvxXvQT7alqj8rohuMGjojIZHigew4kYeOsAt4TPwbc//T3L/N7WsGZERNM47o",
	"D/Zdgq7eDtr/4qZE3SAnatgQj5vk9s9TVB2trtj746X1sJTGeXTrHTPBteNy8kWWqY5m+KJkD81Kq7P1",
	"HPpl/zkAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
